[global]
color = "#544587"
focused_color = "#74af39" 
icon = "󰲌" 
size = "10pt" 

[app_id]
firefox = { icon = "󰈹" }
terminator = { icon = "" }
thunderbird = { icon = "󰇮" }
thunar = { icon = "" }

[class]
jetbrains-idea-ce = { icon = "󰙯" }

[title]
".*VSCodium" = { icon = "󰨞" }
".*Discord" = { icon = "󰙯" }
"Spotify" = { icon = "" }