format = """
[┌─](bright green)$time $all\
[└─>](green) $username@$hostname $character"""

[character]
success_symbol = '[=>](green)'

[time]
disabled = false
format = '[\[$time\]](bright green) '
time_format = '%T - %a, %d/%b/%y'
utc_time_offset = 'local'

[directory]
truncation_length = 1
truncation_symbol = '…/'

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](red) '
disabled = false

